var listData = {};
listData = {
	"success": "ok",
	"data": {
		"list": [{
				"hasImg": "tuijian1",
				"title": "投稿011期 | 寒潮来了，春天还会远嘛？",
				"describe": "码上人生",
				"describe1": "JAVA开发工程师",
				"oldmoney": "￥219.00",
				"newmoney": "￥266.00",
				"allclass": "共21小节",
				"study": "107浏览·1推荐·0评论",
				"coverImg": "img/img/img01.jpg",
				"articleQb": "all",
				"articleqita": "推荐",
				
				"sysId": 1,
			},{
				"hasImg": "tuijian2",
				"title": "两小时学会 Node.js stream",
				"describe": "双越",
				"describe1": "Web前端工程师",
				"oldmoney": "",
				"newmoney": "￥9.99",
				"allclass": "共8小节",
				"study": "",
				"coverImg": "img/img/img01.jpg",
				"articleQb": "all",
				"articleqita": "推荐",
				"sysId": 1,
			},
			{
				"hasImg": "hasImgNYC",
				"title": "理解JavaScript的this",
				"describe": "",
				"describe1": "",
				"oldmoney": "",
				"newmoney": "",
				"allclass": "",
				"study": "33浏览·0推荐·0评论",
				"coverImg": "img/img/img01.jpg",
				"articleQb": "",
				"articleqita": "推荐",
				"sysId": 1,
			},
			{
				"hasImg": "hasImgYC",
				"title": "Java开发人员工作面试必备Linux命令",
				"describe": "",
				"describe1": "",
				"oldmoney": "",
				"newmoney": "",
				"allclass": "",
				"study": "86浏览·2推荐·0评论",
				"coverImg": "img/img/img01.jpg",
				"articleQb": "",
				"articleqita": "推荐",
				"sysId": 1,
			},
			{
				"hasImg": "NoImgYC",
				"title": "Java开发人员工作面试必备Linux命令",
				"describe": "",
				"describe1": "",
				"oldmoney": "",
				"newmoney": "",
				"allclass": "",
				"study": "86浏览·2推荐·0评论",
				"coverImg": "",
				"articleQb": "",
				"articleqita": "推荐",
				"sysId": 1,
			},
			{
				"hasImg": "NoImgYC",
				"title": "Java开发人员工作面试必备Linux命令",
				"describe": "",
				"describe1": "",
				"oldmoney": "",
				"newmoney": "",
				"allclass": "",
				"study": "86浏览·2推荐·0评论",
				"coverImg": "img/img/img01.jpg",
				"articleQb": "",
				"articleqita": "推荐",
				"sysId": 1,
			},
			
			
			
			{
				"hasImg": "hasImgNYC",
				"title": "2018年你们最爱的编程语言发生了什么有趣变化？",
				"describe": "",
				"describe1": "",
				"oldmoney": "",
				"newmoney": "",
				"allclass": "",
				"study": "33浏览·0推荐·0评论",
				"coverImg": "img/img/img02.jpg",
				"articleQb": "",
				"articleqita": "资讯",
				"sysId": 1,
			},
			{
				"hasImg": "hasImgYC",
				"title": "Java开发人员工作面试必备Linux命令",
				"describe": "",
				"describe1": "",
				"oldmoney": "",
				"newmoney": "",
				"allclass": "",
				"study": "86浏览·2推荐·0评论",
				"coverImg": "img/img/img02.jpg",
				"articleQb": "",
				"articleqita": "资讯",
				"sysId": 1,
			},
			{
				"hasImg": "NoImgYC",
				"title": "Java开发人员工作面试必备Linux命令",
				"describe": "",
				"describe1": "",
				"oldmoney": "",
				"newmoney": "",
				"allclass": "",
				"study": "86浏览·2推荐·0评论",
				"coverImg": "",
				"articleQb": "",
				"articleqita": "资讯",
				"sysId": 1,
			},
			{
				"hasImg": "NoImgYC",
				"title": "搭建直播平台过程中的全能“辅助”——流媒体服务器",
				"describe": "",
				"describe1": "",
				"oldmoney": "",
				"newmoney": "",
				"allclass": "",
				"study": "86浏览·2推荐·0评论",
				"coverImg": "",
				"articleQb": "",
				"articleqita": "资讯",
				"sysId": 1,
			},


		]
	}
}